version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=Asimov
      - DB_USER=root
      - DB_PASSWORD=password

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "Asimov"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./datebase/createDatabase.sql:/docker-entrypoint-initdb.d/createDatabase.sql

volumes:
  db_data:
